### ISSUE TITLE
Future data repositories - where to store them?

### ISSUE THREAD

**Issue by DanielKotik** [mala-project/mala#165]
We will have large data repositories in the future and we need to discuss where to host them.

Background information:

We have a small (~ 33MB) [test data repository](https://github.com/mala-project/test-data) with binary data (Numpy arrays, pickled Python objects etc.) For good reasons such binary data should usually not reside inside a git repository. If this is unavoidable or useful for other reasons one should then make use of [git lfs](https://git-lfs.github.com/). At first we have done so for our test data repo. GitHub however not only puts limits on the lfs storage quota (which is of course higher than for a normal git repo):

![grafik](https://user-images.githubusercontent.com/28047702/124280917-824b4a80-db49-11eb-8794-0b1b3db91a65.png)

but also on the bandwidth (1 GB of bandwidth per month). This has already prevented us from the use of our test data repo within the cpu test pipeline. For this reason and because of the small size of our binary test data, we've moved again away from using git lfs.

For future data repositories with huge amount of data (~GBs) we have to think about alternative hosting services. Things to keep in mind are:

- documentation of the repositories content (that's why it's a bad idea to store data inside a docker container which lives somewhere in a registry - the data is almost hidden, where to put a description of the data?)
- reproducible research, citability (getting a DOI from Zenodo, RODARE, figshare or some other more data specialised hosting service)
- version control (git lfs, [DVC](https://dvc.org/))
- FAIR data: Findability, Accessibility, Interoperability and Reusability

There is a lot of literature out on this topic; to list a few:

- https://web.archive.org/web/20190503003656if_/https://towardsdatascience.com/why-git-and-git-lfs-is-not-enough-to-solve-the-machine-learning-reproducibility-crisis-f733b49e96e8?gi=ec1787bd9ed6
- https://www.nature.com/sdata/policies/repositories#physics

**Comment by RandomDefaultUser** [comment]
I think we need to prioritize this higher up; In its current form, the test data repo may have a LDOS, but it is by nature inaccurate due to the size limitations. If we had a bigger data repo, we could host physically correct data.

**Comment by acangi** [comment]
Our default data repository is [RODARE](https://rodare.hzdr.de). While it is well integrated with our systems, it has the drawback that an individual file cannot be accessed, but the entire dataset needs to be downloaded. 

An alternative to RODARE might be the Jülich repository [b2share](https://b2share.fz-juelich.de/). It is similar to RODARE and allows for accessing individual files of a larger dataset. 

Nevertheless, RODARE is currently our first choice. We should, therefore, bring this issue to the attention of the developers and see whether this single-file access can be made available as a new feature in RODARE.

**Comment by RandomDefaultUser** [comment]
Since there has been no further discussion here and the RODARE workflow seems established, I will be closing this for now.

**Comment by DanielKotik** [comment]
> Since there has been no further discussion here and the RODARE workflow seems established, I will be closing this for now.

@RandomDefaultUser What exactly do you mean by "RODARE workflow seems established"?

**Comment by RandomDefaultUser** [comment]
You mentioned in your original comment: "For future data repositories with huge amount of data (~GBs) we have to think about alternative hosting services" 

We are storing all of our research data (e.g., LDOS and bispectrum data for our publications) in RODARE. So I would argue we have found an established workflow there.
