### ISSUE TITLE
Need a DOI

### ISSUE THREAD

**Issue by acangi** [mala-project/mala#220]
I suggest we submit/register MALA at ZENODO following @DanielKotik's suggestion.

**Comment by DanielKotik** [comment]
@RandomDefaultUser and me decided to go for a DOI once we have made the v0.2.0 release. This release includes the `CITATION.cff` file which gives us control over the details of what Zenodo includes in the bibliographic information along with the DOI. I will take care of this as soon as PR #216 is completed.
