### ISSUE TITLE
doc: tensorboard docs point to HZDR infohub web page

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#225]
https://mala-project.github.io/mala/install/tensorboard_setup.html points to https://fwcc.pages.hzdr.de/infohub/hpc/storage.html . That is accessible by people having an HZDR LDAP account, or well everybody else can log in with github creds, so it is not really hidden, but still. 

Users new to the project might not know  what HZDR is, so a few explanatory words might help.

**Comment by RandomDefaultUser** [comment]
Closed with #255
