### ISSUE TITLE
Revert Docker image from `latest` to a tagged `build`

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#265]
Currently, we build with the `continuumio/miniconda3:latest` to get the latest SWIG version, but hopefully this will become obsolete before the next release.

**Comment by DanielKotik** [comment]
The most current, versioned image is `continuumio/miniconda3:4.10.3` which is based on Debian 10, for which only SWIG Version 3.0.12 is available. The `latest` tag is on the other hand based on Debian 11 with SWIG Version 4.0.2.

Either a stable version of `continuumio/miniconda3` based on Debian 11 will be available by the time of the major release of MALA or we will have to compile a recent version of SWIG within the Docker image, or downgrade and fix the version of `oapackage` (which uses SWIG).
