### ISSUE TITLE
Port LAMMPS descriptor calculation to GPU

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#399]
For more efficient inference, it would be advantageous to have a GPU accelerated version of the descriptor version of LAMMPS. 
This includes these steps:

1. Check that the version of LAMMPS we use (https://github.com/athomps/lammps/tree/mala) is in principle working on GPU
2. Test that the descriptor calculation still gives correct results when compiled with GPU support
3. Move descriptor calculation (i.e., all `compute_grid_local` calls) to GPU, if they are not there by default (which they shouldn't be, at least not fully)

**Comment by lokamani** [comment]
we need to converge here on a set of modules we use for all the parts of MALA-Workflow. CUDA-Version, foss/intel etc.

**Comment by RandomDefaultUser** [comment]
That's a very good point. Maybe that should be one of the first topics of the coming hackathon (we should document it here then of course).
