### ISSUE TITLE
Set new defaults

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#410]
For the new MALA version we should decide what options we want to have as a default. E.g.: Should OpenPMD be the default value, should certain performance enhancements (see #409) be made the default, etc.; MALA should keep a balance between performance and stabilitiy.

**Comment by elcorto** [comment]
We will not make openPMD the default for 1.2.0, but need to document the way to use it.

**Comment by RandomDefaultUser** [comment]
OpenPMD has been documented for now!
