### ISSUE TITLE
Add OpenPMD read support for data shuffling and parallelize

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#417]
#416 adds a functionality to shuffle data with MALA. 
However, so far only numpy data can be read, and it would be very good to have OpenPMD reading capabilities. Moreover, this could then lead to some parallelization, making the shuffling very fast.

**Comment by RandomDefaultUser** [comment]
To give a more complete breakdown of what needs to be done:

- [ ] Add OpenPMD support in the `DataShuffler` class (currently, this only works with numpy memmaps to load chunks of data into memory, one at a time; this should be fully possible with OpenPMD as well)
- [ ] Add OpenPMD support in the `MultiLazyLoadDataLoader` (this only requires slight adaptions and reading the data set type from the saved data set) 
- [ ] Refactor the data loading statement in the `DataHandler` class to ensure direct array writing (the numpy implementation already does that, for OpenPMD it wasn't possible up until now because we used FP64 data - now it should work.)

**Comment by franzpoeschel** [comment]
- [ ] Add openPMD to CI pipeline

**Comment by franzpoeschel** [comment]
> Moreover, this could then lead to some parallelization, making the shuffling very fast.

We would need to be careful, as the two obvious approaches to parallelization here (**1.** each rank reads from one file and writes to multiple or **2.** each rank reads from multiple files and writes to one) both have a bad scaling behavior for the number of file handles.
I think that this is possible to avoid by looping synchronously:
```
pseudo code for rank i:

open input file i
for each output_file; do
    open output file synchronously with all other ranks
    shuffle portion from input file into output file
    close output file synchronously with all other ranks
done
```
