### ISSUE TITLE
Building TEM with `cmake`-built QE not supported

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#468]
`mala/external_modules/total_energy_module/build_total_energy_module.sh` needs to be adapted to work with a QE built with `cmake`. Note that the traditional `configure + make` works, this is just for documenting the issue.

Below are the build steps (HZDR hemera cluster) and things that need to be fixed.

```sh
$ srun --time=02:00:00 -A haicu -p haicu_a100,gpu,defq -n16 --pty bash -l -i
$ ml gcc/7.3.0 openmpi/4.1.1 fftw/3.3.10-ompi411 cmake/3.26.1 openblas/haswell/0.3.6

$ cd soft/git
$ git clone git@gitlab.com:QEF/q-e.git
$ cd q-e
$ git checkout qe-7.2
$ rm -rf build
$ find . -regextype posix-extended -regex '.+\.(so|o|a|mod)$' | xargs rm
$ mkdir build
$ cd build
$ cmake ../ -DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_C_COMPILER=gcc -DBUILD_SHARED_LIBS=yes -DQE_FFTW_VENDOR=FFTW3 -DBLA_VENDOR=OpenBLAS
$ make -j16 pw
$ ctest -j16
```

Check lib paths.

```sh
$ grep -E '^(LAPACK|BLAS|FFTW)' CMakeCache.txt | grep -v :INTERNAL
BLAS_openblas_LIBRARY:FILEPATH=/trinity/shared/pkg/numlib/openblas/0.3.6/haswell/gcc/7.3.0/lib/libopenblas.so
FFTW3_DOUBLE:FILEPATH=/trinity/shared/pkg/numlib/fftw/3.3.10/gcc/7.3.0/openmpi/4.1.1/lib/libfftw3.so
FFTW3_INCLUDE_DIRS:PATH=/trinity/shared/pkg/numlib/fftw/3.3.10/gcc/7.3.0/openmpi/4.1.1/include
LAPACK_openblas_LIBRARY:FILEPATH=/trinity/shared/pkg/numlib/openblas/0.3.6/haswell/gcc/7.3.0/lib/libopenblas.so
```

Adapt `build_total_energy_module.sh`

```sh
linalg="-L/trinity/shared/pkg/numlib/openblas/0.3.6/haswell/gcc/7.3.0/lib/ -I/trinity/shared/pkg/numlib/openblas/0.3.6/haswell/gcc/7.3.0/include/ -lopenblas"
fftw="-L/trinity/shared/pkg/numlib/fftw/3.3.10/gcc/7.3.0/openmpi/4.1.1/lib/ -I/trinity/shared/pkg/numlib/fftw/3.3.10/gcc/7.3.0/openmpi/4.1.1/include -lfftw3"
```

Issues:

* all compiled object files are in `q-e/build`, need to adapt paths in `build_total_energy_module.sh`
* using `$root_dir/build` instead of `$root_dir` is not enough, e.g. there is no `$root_dir/build/PW/src`
* check if all linker `-L` and and include `-I` paths need to be adapted
* not sure where to copy the `src=${mod_name}.f90` file as we do in `cp -v $src $pw_src_path/` where `$pw_src_path=$root_dir/PW/src`
* `$root_dir/XClib/xc_lib.a` is not build, also not in `$root_dir/build/XClib`, what to link instead?

**Comment by RandomDefaultUser** [comment]
Hi @elcorto I am trying to close some old issues and came across this one. 
How would you propose we go about closing this issue? 
I originally wanted to propose developing a second shell script (or heavily adapting the existing one) to make this work automatically. However, I am wondering if maybe we should just move what is written here to the documentation? Maintaining two installation scripts can be a bit much for our somewhat limited resources. Additionally, since we want to move away from QE eventually, it may be unnecessary development work. 

What do you think?

**Comment by elcorto** [comment]
Because of the open issues mentioned above (`cmake` does not work) I'd not replicate all of the above and instead just say that QE has to be built with normal configure+make and then link to this issue here.

**Comment by RandomDefaultUser** [comment]
Since this has been done in https://github.com/mala-project/mala/pull/552 I would close this issue here for now? 
In the sense that we will likely never adapt the TEM to `cmake` if we are moving away from it as a whole.

**Comment by elcorto** [comment]
True, forgot about that, thanks :-)
