### ISSUE TITLE
Implement mechanism to reorder tests

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#478]
It would be good for the test suite to be able to specify test execution order. With this, we may also be able to address #475 . Solutions exist, we just have to implement them: https://stackoverflow.com/questions/70738211/run-pytest-classes-in-custom-order/70758938#70758938

**Comment by pcagas** [comment]
This is possible with `pytest` plugins like [dependency](https://pytest-dependency.readthedocs.io/en/stable/index.html) and [order](https://pytest-order.readthedocs.io/en/stable/index.html); however, these don't work with [pytest-xdist](https://pytest-xdist.readthedocs.io/en/stable/index.html).

Issue #475 is being resolved with PR #517.
