### ISSUE TITLE
Adopt a code formatting standard

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#501]
We discussed the adoption of a code formatting standard, using for instance `black`.

## Implications for feature branches

Formatting would mean a 1-time black-ify of the whole code base and one commit. If this is done on `delevop` then all maintainers of feature branches must also black-format all code in their branch before merges happen in the future.

@franzpoeschel suggested a rebase workflow using https://github.com/franzpoeschel/reformat-rebase, which was used to format https://github.com/openPMD/openPMD-api.

Another merge-based workflow could be (0) format `develop` and commit, then sync with formatted `delevop` by (1) formatting code in `feature-branch`

```sh
$ git checkout feature-branch
$ find -name "*.py" | xargs black
```

and (2) merging `develop` into `feature-branch`.

```sh
$ git checkout feature-branch
$ git merge develop
```

This won't alter `delevop` and only add a merge commit to `feature-branch`. It makes sure that `feature-branch` is in sync with `develop`. Any further development in `feature-branch` can later be merged into `develop` as usual.

```sh
$ git checkout develop
$ git merge feature-branch
```

## Tools

As an alternative to `black`, one could use the now popular `ruff` linter, which has a [`ruff format`](https://docs.astral.sh/ruff/formatter/) command. It is back-compatible, faster and offers some more features such as doc string code formatting. But then again, `black` is more stable while  `ruff` is more actively developed.

**Comment by franzpoeschel** [comment]
> then all maintainers of feature branches must also black-format all code in their branch before merges happen in the future

Two suggestions on how to ensure this:

1. Have a CI run that checks for the formatting and fails if the new code is not formatted. [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu) does this.
2. Use pre-commit with a format hook. Developers can either install pre-commit locally, then all code will be formatted when committing, otherwise there is a pre-commit bot that will push a fixup commit on badly formatted pull requests. [openPMD-api](https://github.com/openPMD/openPMD-api/) does this.

**Comment by elcorto** [comment]
I have started using `ruff` for formatting and linting with good results in other projects. Here are the relavant configs for reference in the way I used them:

* [config in pyproject.toml](https://github.com/elcorto/psweep/blob/main/pyproject.toml#L84-L102)
* [`pre-commit` config](https://github.com/elcorto/psweep/blob/main/.pre-commit-config.yaml)
* [lint and format check in CI](https://github.com/elcorto/psweep/blob/main/.github/workflows/tests.yml#L49-L54)

I think in mala there is no linting so far, [apart from docstring checks with `pydocstyle`](https://github.com/mala-project/mala/blob/develop/.github/workflows/gh-pages.yml#L27-L32) which is OK. I'd start minimal and use either `ruff` or `black` for formatting. 

The only config that should be defined up front is the line length (default is 88 in `black` and `ruff`).  For both tools, that can be configured in `pyproject.toml`, wich mala doesn't have currently. I'm not sure if using `pyproject.toml` (just to hold configs) and `setup.py` side-by-side will work, though. This *might* be a good time to move to `pyproject.toml` but of course implies some more work.

**Comment by RandomDefaultUser** [comment]
Thank you both for your input! 
From reading this, I garner that the first thing I should do is to "blackify" the existing codebase and add a `.pre-commit-config.yaml` to MALA. I will get on to this. 

I have no epxerience/strong opinion w.r.t whether we should use `black` or `ruff`, but I am  under the impression that the former was more popular during our last discussion, so I would opt for that. 

I will check out whether `pyproject.toml` and `setup.py` can coexist, and if not, we can make the switch. We have to do so eventually anyway.

Does that sum it up or am I forgetting something?

**Comment by elcorto** [comment]
Yes that's it. Thanks for looking into that! Some final comments:

* One-time `black`-ify: The thing you need to define up-front is the line length. Default is 88, my personal choice would be 79, which you can set by `black -l 79 ... all .py files ...` if there is no `pyproject.toml` with

  ```toml
  [tool.black]
  line-length = 79
  ```

  Of course I'm fine with whatever line length, it's just that the project (well, the main dev :)) has to decide this once and set it. Note: If we use 88, there is no need to create a `pyproject.toml` just for that. But we may want that anyway to ease configuring other tools that we might use later.

* `black` vs. `ruff`: since the goal for now is "just" formatting, I'd go with `black` since that is pretty stable. `ruff` is nice if used as a linter as well, but if using dependabot (which we don't currently), we'd see ruff update PRs almost weekly :)

* The switch to `pyproject.toml` should be straight-forward, esp. since we don't do only standard stuff in `setup.py`.
