### ISSUE TITLE
SNAP data overwritten for simultaneous pre-processing in same directory

### ISSUE THREAD

**Issue by timcallow** [mala-project/mala#502]
When pre-processing SNAP data with lammps, there is an issue if multiple jobs are launched simultaneously from the same directory. The data for one snapshot is sometimes overwritten by the data corresponding to a different snapshot, because of the way mala calls lammps. 

In the best case, this behaviour should be fixed so that multiple pre-processing jobs can be invoked simultaneously in the same directory. In the meantime, a warning to the user should be printed.

**Comment by RandomDefaultUser** [comment]
Closed with #518
