### ISSUE TITLE
Issue creating an arbitrary number of snapshots

### ISSUE THREAD

**Issue by timcallow** [mala-project/mala#509]
When one tries to create an arbitrary number of snapshots using the `number_of_shuffled__snapshots` parameter in `data_shuffler.shuffle_snapshots`, an exception is raised if the number of snapshots requested is not an exact divisor of the number of data points. 

This means the burden is on the user to find an exact divisor, which is particularly inconvenient when one has a weird number of total grid points, which is quite common when mixing different mass densities. Since it isn't necessary for the snapshots to have exactly the same number of grid points, I would suggest to go with one of the following solutions:

1. The "last" snapshot ends up with extra or fewer grid points
2. All snapshots have the same number of grid points, any excess data is ignored (ok if lots of snapshots are requested, probably not so good if only a small number requested)
3. The closest number to the one requested that is also an exact divisor is sought

Imo, solution 1 is easiest and also best. The difference in the snapshot size will be very minor, considering the number of grid points we typically deal with. But @RandomDefaultUser let me know your thoughts. I can open a PR to implement a fix if you agree this is something to be fixed

**Comment by RandomDefaultUser** [comment]
Thanks for bringing this to my attention! I think this is just an artifact of back when all snapshots in a training set had to have the same dimensions. I think at some point I also had something like 3 cooked up, but that was probably before you made the adjustments for multiple grid sizes during the mass density project.

I agree that option 1 sounds like the best one. If you want to take care of this and open a PR, I would highly appreciate that! :)

**Comment by RandomDefaultUser** [comment]
Closed by #570.
