### ISSUE TITLE
Avoid CI runs when PR is still in "draft" mode

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/mala#514]
A Draft PR should not activate the CI, this would reduce overall Github action time required.

**Comment by DanielKotik** [comment]
I suggest the use of [event activity types](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-event-activity-types) for fine control when workflows are triggered.

**Comment by DanielKotik** [comment]
As recognised by @RandomDefaultUser, the current implementation prevents the CI from running on normal PRs, only switching to draft and back to ‘ready for review’ triggers the CI runs (or doing this manually). This is not ideal. I will try to implement [this](https://stackoverflow.com/questions/73948443/github-actions-running-a-workflow-on-non-draft-prs) solution.
