### ISSUE TITLE
Align Python versions througout MALA

### ISSUE THREAD

**Issue by DanielKotik** [mala-project/mala#526]
At the moment we use/mention different Python versions at several places, e.g.

- https://github.com/mala-project/mala/blob/e6e831b4edd14755ecaa3c5deffbefa4d0939169/docs/source/install/installing_mala.rst?plain=1#L8
- https://github.com/mala-project/mala/blob/e6e831b4edd14755ecaa3c5deffbefa4d0939169/.github/workflows/publish-to-pypi.yml#L25
- https://github.com/mala-project/mala/blob/e6e831b4edd14755ecaa3c5deffbefa4d0939169/.github/workflows/gh-pages.yml#L22
- https://github.com/mala-project/mala/blob/e6e831b4edd14755ecaa3c5deffbefa4d0939169/install/mala_cpu_base_environment.yml#L6
- https://github.com/mala-project/mala/blob/e6e831b4edd14755ecaa3c5deffbefa4d0939169/install/mala_cpu_environment.yml#L116

We should ensure to support at least *one* Python version that suits the mala package *and* building of the documentation at the time. In a next step we might think about supporting multiple Python version and run pipelines for to cover these different versions, see for example: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Bonus**:   add badge of supported Python verions

**Comment by elcorto** [comment]
Also this:

https://github.com/mala-project/mala/blob/0fed9cc707979d2cdc0227c7a3eed4fd1fbbd291/.pre-commit-config.yaml#L13

**Comment by elcorto** [comment]
I also suggest to have the mininmal (and maximal if needed, see #559) supported version in `pyproject.toml`, or `setup.py` if we continue using it.
