### ISSUE TITLE
Crash when using GPU in descriptor calculation

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#551]
When using the fairly standard script below on a GPU machine I see a crash (no logs, however), which I traced to `predictor.predict_for_atoms(atoms)` -> `Predictor.data.descriptor_calculator.calculate_from_atoms(...)`.

My *guess* is that it may have something to do with LAMMPS? Before I dig around any further, maybe someone has concrete ideas for how to debug this? Thanks.

liblammps info:

```sh
$ ldd ~/.virtualenvs/mala-sys/lib/python3.11/site-packages/lammps/liblammps.so
        linux-vdso.so.1 =>  (0x00002aaaaaacd000)
        libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00002aaaab558000)
        libpng15.so.15 => /lib64/libpng15.so.15 (0x00002aaaab7ad000)
        libz.so.1 => /home/user42/soft/git/spack/opt/spack/linux-centos7-x86_64_v3/gcc-7.3.0/zlib-1.2.13-dbztj356ku7tfdjtyldbyrgt2rrtlziq/lib/libz.so.1 (0x00002aaaab9d8000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaabbef000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaabef1000)
        libgomp.so.1 => /trinity/shared/pkg/compiler/gcc/7.3.0/lib64/libgomp.so.1 (0x00002aaaac0f5000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac323000)
        libstdc++.so.6 => /trinity/shared/pkg/compiler/gcc/7.3.0/lib64/libstdc++.so.6 (0x00002aaaac53f000)
        libgcc_s.so.1 => /trinity/shared/pkg/compiler/gcc/7.3.0/lib64/libgcc_s.so.1 (0x00002aaaac8c1000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaacad8000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
```

Other:

* Python 3.11.2
* torch 2.2.1+cu121

Script:

```py
import os

import ase.io

import mala
from mala.datahandling.data_repo import data_repo_path


data_path = os.path.join(data_repo_path, "Be2")

parameters = mala.Parameters()
parameters.use_gpu = True
parameters.data.input_rescaling_type = "feature-wise-standard"
parameters.data.output_rescaling_type = "normal"
parameters.network.layer_activations = ["LeakyReLU"]
parameters.running.max_number_epochs = 10
parameters.running.mini_batch_size = 40
parameters.running.learning_rate = 1e-5
parameters.running.trainingtype = "Adam"

parameters.targets.target_type = "LDOS"
parameters.targets.ldos_gridsize = 11
parameters.targets.ldos_gridspacing_ev = 2.5
parameters.targets.ldos_gridoffset_ev = -5

parameters.descriptors.descriptor_type = "Bispectrum"
parameters.descriptors.bispectrum_twojmax = 10
parameters.descriptors.bispectrum_cutoff = 4.67637

data_handler = mala.DataHandler(parameters)
data_handler.add_snapshot(
    "Be_snapshot0.in.npy", data_path, "Be_snapshot0.out.npy", data_path, "tr"
)
data_handler.add_snapshot(
    "Be_snapshot1.in.npy", data_path, "Be_snapshot1.out.npy", data_path, "va"
)
data_handler.prepare_data()

parameters.network.layer_sizes = [
    data_handler.input_dimension,
    100,
    data_handler.output_dimension,
]
network = mala.Network(parameters)

trainer = mala.Trainer(parameters, network, data_handler)
trainer.train_network()
additional_calculation_data = os.path.join(data_path, "Be_snapshot0.out")

predictor = mala.Predictor(
    params=parameters, network=network, data=data_handler
)

predictor.target_calculator.read_additional_calculation_data(
    additional_calculation_data
)

atoms = ase.io.read(os.path.join(data_path, "Be_snapshot3.out"))

# XXX crash here, in Predictor.data.descriptor_calculator.calculate_from_atoms(...)
ldos = predictor.predict_for_atoms(atoms)
```

**Comment by elcorto** [comment]
It is indeed lammps, setting `parameters.use_lammps = False` works but of course this is much slower.

**Comment by RandomDefaultUser** [comment]
So the issue appears when you call LAMMPS while using a GPU, correct? Did you set up LAMMPS with Kokkos and CUDA support? I am asking because an `ldd` on my GPU LAMMPS version of hemera looks a bit different:

```bash
fiedle09@hemera5:~/tools/lammps_gpu/build$ ldd liblammps.so
./liblammps.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./liblammps.so)
./liblammps.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./liblammps.so)
./liblammps.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./liblammps.so)
./liblammps.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./liblammps.so)
	linux-vdso.so.1 =>  (0x00002aaaaaacd000)
	libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00002aaaaf080000)
	libpng15.so.15 => /usr/lib64/libpng15.so.15 (0x00002aaaaf2d5000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00002aaaaf500000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00002aaaaf716000)
	libmpi.so.40 => /trinity/shared/pkg/mpi/openmpi/4.0.4/gcc/8.2.0/lib/libmpi.so.40 (0x00002aaaafa18000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00002aaaafea5000)
	libcuda.so.1 => not found
	libcudart.so.11.0 => not found
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002aaab00cb000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00002aaab02cf000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002aaab04d7000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaab06f3000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00002aaab09fb000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00002aaab0c11000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
	libopen-rte.so.40 => /trinity/shared/pkg/mpi/openmpi/4.0.4/gcc/8.2.0/lib/libopen-rte.so.40 (0x00002aaab0fdf000)
	libopen-pal.so.40 => /trinity/shared/pkg/mpi/openmpi/4.0.4/gcc/8.2.0/lib/libopen-pal.so.40 (0x00002aaab1300000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x00002aaab1856000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00002aaab1a6d000)
	libpmi2.so.0 => /lib64/libpmi2.so.0 (0x00002aaab1c86000)
	libpmi.so.0 => /lib64/libpmi.so.0 (0x00002aaab1e9f000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002aaab20a5000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00002aaab22a8000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00002aaab2515000)
	libslurmfull.so => /usr/lib64/slurm/libslurmfull.so (0x00002aaab2736000)
``` 

When using GPU for inference, LAMMPS will always try to use Kokkos for inference. There is currently no standard way to use CPU for LAMMPS and then GPU for the neural network (the reasoning being that the descriptor calculation is usually way slower than the NN inference, so just accelerating the latter usually doesn't make much sense). If necessary, we can of course also implement this.

**Comment by elcorto** [comment]
No my LAMMPS is not built against CUDA.

[The docs say](https://mala-project.github.io/mala/install/installing_lammps.html) "PKG_KOKKOS=yes: Enables the Kokkos package which is needed to calculate bispectrum descriptors on a GPU. Without this option, bispectrum descriptor calculation will solely be performed on CPU."

That sounds to me as if it was possible to mix GPU torch and CPU LAMMPS ops, but you say that's not possible. This means that `parameters.use_gpu = True` also effects `Predictor.data.descriptor_calculator.calculate_from_atoms(...)` automatically? Could you maybe point me to the spot in the code where this is happening?

If this is the case, then no there is no need to implement the mixing case I think, I'll rebuild LAMMPS then -- or dig down and try to force the LAMMPS CPU code path, whichever is quicker.

**Comment by RandomDefaultUser** [comment]
Ah, I see the problem. 

Yes, the docs is not really specific enough in this case. Whenever `parameters.use_gpu = True`, the predictor class will try to use Kokkos in the LAMMPS section of the code, which, as you have found out, may break. 
Enabling Kokkos for the descriptor calculation happens right when the LAMMPS instance is set up: https://github.com/mala-project/mala/blob/d59a57f907f266310da2e981eecbc4492fb089ac/mala/descriptors/descriptor.py#L803
This function is called from `Predictor.data.descriptor_calculator.calculate_from_atoms(...)`. 

So changing the code is probably not necessary than, but should we maybe clarify the documentation? Do you maybe, based on your experience, have a suggestion?

**Comment by elcorto** [comment]
Thanks for the clarification. Actually the [docs on GPU usage](https://mala-project.github.io/mala/advanced_usage/predictions.html#predictions-on-gpu) already state what you said, I wasn't aware of that.

In the "Build LAMMPS" I referred to, maybe one can add a small note and link to the GPU part of the docs.

**Comment by RandomDefaultUser** [comment]
Sounds good, let's do that!
