### ISSUE TITLE
Don't fix Python version in `.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#568]
We have 

https://github.com/mala-project/mala/blob/0fed9cc707979d2cdc0227c7a3eed4fd1fbbd291/.pre-commit-config.yaml#L8-L13

but on a system with only Python 3.11 available, we get

```sh
$ pre-commit run -a
An unexpected error has occurred: CalledProcessError: command: ('/path/to/python/3.11.2/bin/python3.11', '-mvirtualenv', '/home/user42/.cache/pre-commit/repokdlvjmqs/py_env-python3.12', '-p', 'python3.12')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.12'
stderr: (none)
```

We could also set this to python3.11, but I guess the more portable way is to rely on black's auto-detection and remove that setting.

**Comment by RandomDefaultUser** [comment]
I agree that as long as we don't enforce a python version across MALA (and maybe even then?) we shouldn't enforce a specific version here. Thanks for the PR!
