### ISSUE TITLE
`during_training_metric` used as validation loss

### ISSUE THREAD

**Issue by elcorto** [mala-project/mala#572]
When using `parameters.running.during_training_metric`, the quantity (e.g. band energy) is used as validation loss, both in the text log and when fed to tensorboard, which is a bit confusing as it distorts loss plots.

The quantity should probably be reported in addition to the validation loss instead.

**Comment by RandomDefaultUser** [comment]
Hi @elcorto, @nerkulec overhauled the entire error reporting process extensively in his PR #560 . I think this should also address your issue, could you have a look?

**Comment by nerkulec** [comment]
#560 solves the issue
