### ISSUE TITLE
Add coverage to tests

### ISSUE THREAD

**Issue by timcallow** [mala-project/mala#592]
I suggest to add coverage to the tests. At the moment, if someone adds a new feature, the onus is on them to remember to add tests to check that it's working. Also it gives more confidence when making changes if you can see the test-suite is really covering the full range of functionality.

We could set it up so that if the coverage drops below a certain threshold, then the tests fail. This is how I set it up in atoMEC.

What do you think @RandomDefaultUser?

**Comment by RandomDefaultUser** [comment]
I think that sounds like a great idea!

If you have the capacity, feel free to prepare a PR!
